version: 2
registries:
  maven:
    type: maven-repository
    url: https://bin.pega.io/artifactory/repo2-release/
    username: ${{secrets.ENG_ARTIFACTORY_USR}}
    password: ${{secrets.ENG_ARTIFACTORY_PWD}}
  npm:
    type: npm-registry
    url: https://bin.pega.io/artifactory/api/npm/npmjs-dev/
    username: ${{secrets.ENG_ARTIFACTORY_USR}}
    password: ${{secrets.ENG_ARTIFACTORY_PWD}}
  docker:
    type: docker-registry
    url: https://docker-dev.bin.pega.io/
    username: ${{secrets.ENG_ARTIFACTORY_USR}}
    password: ${{secrets.ENG_ARTIFACTORY_PWD}}

updates:
  - package-ecosystem: "gradle"
    directories:
      - "**/*"
    registries: "*"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      major:
        update-types:
          - "major"
        patterns:
          - "*"
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.jetbrains.compose:*"
        versions: [ ">=1.11.0" ] # compose-multiplatform 1.11.0+ does not support iosX64 target
    commit-message:
      prefix: "Dependabot - [Gradle] -"
