name: "Build SDK for Android"
description: "Build SDK for Android platform"
inputs:
  android-version:
    description: "Version of Android to use for downloading Android SDK and emulator e.g. 35"
    required: true
    default: '35'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up cache for Gradle
      id: cache-gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle
        key: gradle-cache

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266719
        packages: 'system-images;android-${{ inputs.android-version }};google_apis;x86_64 platforms;android-${{ inputs.android-version }} platform-tools emulator'
        log-accepted-android-sdk-licenses: false

    - name: Assemble AARs
      env:
        GRADLE: ./gradlew -Dorg.gradle.console=plain --info --no-daemon
      shell: bash
      run: |
        rm -rf release || true
        mkdir release
        $GRADLE :core:assemble :engine:webview:assemble :ui:components:cmp:assemble :ui:renderer:cmp:assemble
        cp core/build/outputs/aar/core.aar release/core.aar
        cp engine/webview/build/outputs/aar/webview.aar release/engine-webview.aar
        cp ui/renderer/cmp/build/outputs/aar/cmp.aar release/ui-renderer-cmp.aar
        cp ui/components/cmp/build/outputs/aar/cmp.aar release/ui-components-cmp.aar

    - uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: release
        retention-days: 1
        compression-level: 0
        if-no-files-found: error
